/**
 * CSV export for the admin tables.
 *
 * The founder's order and customer lists previously had to be generated by hand
 * outside the app whenever anyone wanted to work through them in a spreadsheet.
 * Exports the rows currently loaded and filtered, so what you see is what you
 * get.
 */

/** Quotes a single field. Leading =/+/-/@ are prefixed so spreadsheets treat
 *  them as text instead of executing them as formulas. */
function cell(value: unknown): string {
  if (value === null || value === undefined) return "";
  let text = String(value);
  if (/^[=+\-@]/.test(text)) text = `'${text}`;
  if (/[",\n\r]/.test(text)) return `"${text.replace(/"/g, '""')}"`;
  return text;
}

export function toCsv<T>(rows: T[], columns: Array<{ header: string; value: (row: T) => unknown }>): string {
  const head = columns.map((c) => cell(c.header)).join(",");
  const body = rows.map((row) => columns.map((c) => cell(c.value(row))).join(","));
  return [head, ...body].join("\r\n");
}

/** Triggers a browser download. Prefixed with a BOM so Excel reads UTF-8 names
 *  (Indian customer names and the rupee sign) correctly. */
export function downloadCsv(filename: string, csv: string): void {
  const blob = new Blob([`\uFEFF${csv}`], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

/** `orders-2026-08-24.csv` — dated so repeated exports don't overwrite. */
export function datedFilename(base: string): string {
  return `${base}-${new Date().toISOString().slice(0, 10)}.csv`;
}
