export interface PlaceholderProduct {
  id: string;
  slug: string;
  name: string;
  category: string;
  categoryLabel: string;
  price: number;
  mrp?: number;
  image: string;
  rating: number;
  reviewCount: number;
  badge?: "Best Seller" | "New" | "20% Off";
  dosha?: string[];
}

export const PLACEHOLDER_PRODUCTS: PlaceholderProduct[] = [
  {
    id: "1",
    slug: "kumkumadi-serum",
    name: "Kumkumadi Revitalizing Face Serum",
    category: "skin-care",
    categoryLabel: "FACE SERUM",
    price: 2499,
    mrp: 2999,
    image: "/placeholder.svg",
    rating: 4.8,
    reviewCount: 33,
    badge: "Best Seller",
    dosha: ["Vata", "Pitta"],
  },
  {
    id: "2",
    slug: "ashwagandha-body-oil",
    name: "Ashwagandha Calming Body Oil",
    category: "body-wellness",
    categoryLabel: "BODY OIL",
    price: 899,
    image: "/placeholder.svg",
    rating: 4.6,
    reviewCount: 21,
    badge: "New",
    dosha: ["Vata"],
  },
  {
    id: "3",
    slug: "neem-face-wash",
    name: "Neem & Turmeric Purifying Face Wash",
    category: "skin-care",
    categoryLabel: "CLEANSER",
    price: 499,
    image: "/placeholder.svg",
    rating: 4.5,
    reviewCount: 48,
    dosha: ["Pitta", "Kapha"],
  },
  {
    id: "4",
    slug: "brahmi-hair-oil",
    name: "Brahmi Hair Growth Oil",
    category: "hair-care",
    categoryLabel: "HAIR OIL",
    price: 699,
    image: "/placeholder.svg",
    rating: 4.7,
    reviewCount: 29,
    badge: "20% Off",
    dosha: ["Vata", "Kapha"],
  },
  {
    id: "5",
    slug: "triphala-digestive",
    name: "Triphala Digestive Wellness Capsules",
    category: "body-wellness",
    categoryLabel: "WELLNESS",
    price: 599,
    image: "/placeholder.svg",
    rating: 4.4,
    reviewCount: 15,
    dosha: ["Pitta", "Kapha"],
  },
  {
    id: "6",
    slug: "sandalwood-face-pack",
    name: "Sandalwood & Rose Ubtan Face Pack",
    category: "skin-care",
    categoryLabel: "FACE PACK",
    price: 749,
    image: "/placeholder.svg",
    rating: 4.9,
    reviewCount: 42,
    badge: "Best Seller",
    dosha: ["Vata", "Pitta", "Kapha"],
  },
  {
    id: "7",
    slug: "amla-hair-mask",
    name: "Amla & Hibiscus Hair Mask",
    category: "hair-care",
    categoryLabel: "HAIR CARE",
    price: 549,
    image: "/placeholder.svg",
    rating: 4.5,
    reviewCount: 18,
    dosha: ["Pitta"],
  },
  {
    id: "8",
    slug: "shilajit-energy",
    name: "Himalayan Shilajit Resin",
    category: "body-wellness",
    categoryLabel: "WELLNESS",
    price: 1999,
    image: "/placeholder.svg",
    rating: 4.8,
    reviewCount: 56,
    badge: "New",
    dosha: ["Vata", "Kapha"],
  },
  {
    id: "9",
    slug: "rose-face-mist",
    name: "Kannauj Rose Hydrating Face Mist",
    category: "skin-care",
    categoryLabel: "FACE MIST",
    price: 649,
    image: "/placeholder.svg",
    rating: 4.6,
    reviewCount: 24,
    dosha: ["Pitta", "Vata"],
  },
  {
    id: "10",
    slug: "vata-balance-oil",
    name: "Vata Balance Abhyanga Oil",
    category: "body-wellness",
    categoryLabel: "BODY OIL",
    price: 1299,
    image: "/placeholder.svg",
    rating: 4.7,
    reviewCount: 31,
    dosha: ["Vata"],
  },
  {
    id: "11",
    slug: "bhringraj-oil",
    name: "Bhringraj Hair Oil",
    category: "hair-care",
    categoryLabel: "HAIR OIL",
    price: 599,
    image: "/placeholder.svg",
    rating: 4.5,
    reviewCount: 27,
    dosha: ["Vata", "Pitta"],
  },
  {
    id: "12",
    slug: "turmeric-moisturizer",
    name: "Turmeric & Manjistha Glow Cream",
    category: "skin-care",
    categoryLabel: "MOISTURIZER",
    price: 899,
    image: "/placeholder.svg",
    rating: 4.6,
    reviewCount: 19,
    dosha: ["Pitta", "Kapha"],
  },
];

export const getBestSellers = () => PLACEHOLDER_PRODUCTS.slice(0, 8);
export const getNewArrivals = () => PLACEHOLDER_PRODUCTS.slice(4, 8);
